### ISSUE TITLE
인증번호 다시 받기 대기 시간 삭제

### ISSUE THREAD

**Issue by HeathChang** [FitBuddyProject/fitbuddy-be#12]
<img width="283" alt="Screenshot 2024-11-01 at 12 04 13 AM" src="https://github.com/user-attachments/assets/80cad14e-dee3-4a07-bd62-2494c43ad8e7">

인증번호 다시받기 버튼 있는데,
동일한 번호의 경우는 다시 못받음

**Comment by newkayak12** [comment]
local일 경우 무시하도록 하겠습니다.

**Comment by HeathChang** [comment]
+ 이거 근데 로컬이 아니여도, 다시 받기 한 경우는 보내야 되지 않을까요 ???

**Comment by newkayak12** [comment]
일단 메시지 입력 기간 내(프론트) 기준이 초과되면 다시 보낼 수 있게 되어 있습니다

만일 말씀하신대로 하면 보내기를 누를 때마다 전송되며 이 부분에 대해서 '방어적으로 생각하는 게 좋지 않나?'합니다

좋은 의견 주시면 취합하여 수정하겠습니다
