### ISSUE TITLE
버디 enum 명칭 변경 요청

### ISSUE THREAD

**Issue by ssyeon612** [FitBuddyProject/fitbuddy-be#8]
AS-IS: CHICKEN(치킨), RABBIT(토끼), DUCK(오리)
TO-BE: CHICKEN(치킨), OTTER(수달), MONSTER(이상이)

Buddy: {
    CHICKEN: {
	name: "삐약이",
        description: "삐약이"
  },   
OTTER: {
	name: "수달이",
        description: "수달이"
  },   
MONSTER: {
	name: "이상이",
        description: "이상이"
  }
}

**Comment by newkayak12** [comment]
확인했습니다.
